import { Mulish } from "next/font/google";
import Header from "./components/Header";
import "./globals.css";
import Footer from "./components/Footer";
import { Providers } from "./redux/providers";

const mulish = Mulish({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
  display: "swap",
});

export const metadata = {
  title: "ShopFlare",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={mulish.className}>
        <Providers>
        <Header />
        {children}
        <Footer/>
        </Providers>

      </body>
    </html>
  );
}
